version: "2"
linters:
  enable:
    - asciicheck
    - exhaustruct
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocritic
    - gomodguard
    - importas
    - inamedparam
    - misspell
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - testableexamples
    - unconvert
  settings:
    gocritic:
      disabled-checks:
        - sloppyLen
    gomodguard:
      allowed:
        modules:
          - gopkg.in
    revive:
      rules:
        - name: unused-parameter
          disabled: true
        - name: var-naming
          disabled: true
        - name: var-declaration
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
